In [1]:
import pandas as pd
path = "/Users/ijeomaokoye/IdeaProjects/cdc-health-equity-pipeline/data/raw/SVI_2022_US_county (1).csv"
df = pd.read_csv(path)

In [3]:
print(df.shape)
df.info()
display(df.head(5))
display(df.sample(5, random_state=42))

(3144, 158)
<class 'pandas.DataFrame'>
RangeIndex: 3144 entries, 0 to 3143
Columns: 158 entries, ST to MP_OTHERRACE
dtypes: float64(75), int64(79), str(4)
memory usage: 3.8 MB

,ST,STATE,ST_ABBR,STCNTY,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,M_TOTPOP,...,EP_ASIAN,MP_ASIAN,EP_AIAN,MP_AIAN,EP_NHPI,MP_NHPI,EP_TWOMORE,MP_TWOMORE,EP_OTHERRACE,MP_OTHERRACE
0,1,Alabama,AL,1001,Autauga County,1001,"Autauga County, Alabama",594.454786,58761,0,...,1.1,0.4,0.1,0.1,0.0,0.1,3.3,1.0,0.2,0.3
1,1,Alabama,AL,1003,Baldwin County,1003,"Baldwin County, Alabama",1589.861817,233420,0,...,0.9,0.1,0.2,0.1,0.0,0.1,3.1,0.4,0.4,0.3
2,1,Alabama,AL,1005,Barbour County,1005,"Barbour County, Alabama",885.007619,24877,0,...,0.5,0.1,0.3,0.1,0.0,0.1,1.8,0.7,1.2,0.8
3,1,Alabama,AL,1007,Bibb County,1007,"Bibb County, Alabama",622.469286,22251,0,...,0.3,0.4,0.1,0.1,0.0,0.2,1.7,1.0,0.1,0.1
4,1,Alabama,AL,1009,Blount County,1009,"Blount County, Alabama",644.890376,59077,0,...,0.2,0.2,0.1,0.1,0.2,0.2,2.8,0.7,0.1,0.1

,ST,STATE,ST_ABBR,STCNTY,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,M_TOTPOP,...,EP_ASIAN,MP_ASIAN,EP_AIAN,MP_AIAN,EP_NHPI,MP_NHPI,EP_TWOMORE,MP_TWOMORE,EP_OTHERRACE,MP_OTHERRACE
2993,53,Washington,WA,53077,Yakima County,53077,"Yakima County, Washington",4294.509985,256143,0,...,1.0,0.1,2.5,0.2,0.4,0.2,3.0,0.3,0.2,0.1
2971,53,Washington,WA,53033,King County,53033,"King County, Washington",2115.733007,2254371,0,...,19.3,0.1,0.4,0.1,0.7,0.1,6.5,0.2,0.5,0.1
1064,21,Kentucky,KY,21139,Livingston County,21139,"Livingston County, Kentucky",312.959517,8980,0,...,0.0,0.1,0.0,0.4,0.0,0.4,2.6,0.4,0.0,0.4
1987,37,North Carolina,NC,37191,Wayne County,37191,"Wayne County, North Carolina",553.921675,117480,0,...,1.1,0.2,0.1,0.1,0.1,0.1,3.6,0.5,0.2,0.1
2990,53,Washington,WA,53071,Walla Walla County,53071,"Walla Walla County, Washington",1270.032474,62150,0,...,1.7,0.2,0.3,0.1,0.2,0.1,3.4,0.5,0.1,0.1

In [4]:
missing = df.isna().mean().sort_values(ascending=False)
display(missing.head(5))

ST            0.0
F_UNINSUR     0.0
RPL_THEME4    0.0
SPL_THEMES    0.0
RPL_THEMES    0.0
dtype: float64

In [5]:
print(df["FIPS"].duplicated().sum())
df["FIPS"] = df["FIPS"].astype(str).str.zfill(5)

0

In [6]:
print(df["FIPS"].duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
3139    False
3140    False
3141    False
3142    False
3143    False
Name: FIPS, Length: 3144, dtype: bool

In [2]:
cols = df.columns.tolist()
print(cols)

['ST', 'STATE', 'ST_ABBR', 'STCNTY', 'COUNTY', 'FIPS', 'LOCATION', 'AREA_SQMI', 'E_TOTPOP', 'M_TOTPOP', 'E_HU', 'M_HU', 'E_HH', 'M_HH', 'E_POV150', 'M_POV150', 'E_UNEMP', 'M_UNEMP', 'E_HBURD', 'M_HBURD', 'E_NOHSDP', 'M_NOHSDP', 'E_UNINSUR', 'M_UNINSUR', 'E_AGE65', 'M_AGE65', 'E_AGE17', 'M_AGE17', 'E_DISABL', 'M_DISABL', 'E_SNGPNT', 'M_SNGPNT', 'E_LIMENG', 'M_LIMENG', 'E_MINRTY', 'M_MINRTY', 'E_MUNIT', 'M_MUNIT', 'E_MOBILE', 'M_MOBILE', 'E_CROWD', 'M_CROWD', 'E_NOVEH', 'M_NOVEH', 'E_GROUPQ', 'M_GROUPQ', 'EP_POV150', 'MP_POV150', 'EP_UNEMP', 'MP_UNEMP', 'EP_HBURD', 'MP_HBURD', 'EP_NOHSDP', 'MP_NOHSDP', 'EP_UNINSUR', 'MP_UNINSUR', 'EP_AGE65', 'MP_AGE65', 'EP_AGE17', 'MP_AGE17', 'EP_DISABL', 'MP_DISABL', 'EP_SNGPNT', 'MP_SNGPNT', 'EP_LIMENG', 'MP_LIMENG', 'EP_MINRTY', 'MP_MINRTY', 'EP_MUNIT', 'MP_MUNIT', 'EP_MOBILE', 'MP_MOBILE', 'EP_CROWD', 'MP_CROWD', 'EP_NOVEH', 'MP_NOVEH', 'EP_GROUPQ', 'MP_GROUPQ', 'EPL_POV150', 'EPL_UNEMP', 'EPL_HBURD', 'EPL_NOHSDP', 'EPL_UNINSUR', 'SPL_THEME1', 'RPL_THEME1', 'EPL_AGE65', 'EPL_AGE17', 'EPL_DISABL', 'EPL_SNGPNT', 'EPL_LIMENG', 'SPL_THEME2', 'RPL_THEME2', 'EPL_MINRTY', 'SPL_THEME3', 'RPL_THEME3', 'EPL_MUNIT', 'EPL_MOBILE', 'EPL_CROWD', 'EPL_NOVEH', 'EPL_GROUPQ', 'SPL_THEME4', 'RPL_THEME4', 'SPL_THEMES', 'RPL_THEMES', 'F_POV150', 'F_UNEMP', 'F_HBURD', 'F_NOHSDP', 'F_UNINSUR', 'F_THEME1', 'F_AGE65', 'F_AGE17', 'F_DISABL', 'F_SNGPNT', 'F_LIMENG', 'F_THEME2', 'F_MINRTY', 'F_THEME3', 'F_MUNIT', 'F_MOBILE', 'F_CROWD', 'F_NOVEH', 'F_GROUPQ', 'F_THEME4', 'F_TOTAL', 'E_DAYPOP', 'E_NOINT', 'M_NOINT', 'E_AFAM', 'M_AFAM', 'E_HISP', 'M_HISP', 'E_ASIAN', 'M_ASIAN', 'E_AIAN', 'M_AIAN', 'E_NHPI', 'M_NHPI', 'E_TWOMORE', 'M_TWOMORE', 'E_OTHERRACE', 'M_OTHERRACE', 'EP_NOINT', 'MP_NOINT', 'EP_AFAM', 'MP_AFAM', 'EP_HISP', 'MP_HISP', 'EP_ASIAN', 'MP_ASIAN', 'EP_AIAN', 'MP_AIAN', 'EP_NHPI', 'MP_NHPI', 'EP_TWOMORE', 'MP_TWOMORE', 'EP_OTHERRACE', 'MP_OTHERRACE']

In [ ]:
cols.find