In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [4]:
engine = create_engine("postgresql+psycopg2://ijeomaokoye@localhost:5432/health_equity")
df = pd.read_sql_query("SELECT * FROM analytics.stg_places_cleaned LIMIT 20", engine)
display(df)

,year,state_abbr,state_desc,location_name,data_source,category,measure,data_value_unit,data_value_type,data_value,...,low_confidence_limit,high_confidence_limit,total_population,total_pop_18_plus,location_id,category_id,measure_id,data_value_type_id,short_question_text,geolocation
0,2022,AL,Alabama,Clay,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,11.0,...,9.6,12.4,"14,198","11,235",1027,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,POINT (-85.8606604130173 33.2693085517833)
1,2022,AL,Alabama,Dale,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,35.6,...,34.8,36.4,"49,544","38,039",1045,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-85.6109266826185 31.4316629601359)
2,2022,AL,Alabama,Jackson,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,5.1,...,4.6,5.6,"52,891","42,087",1071,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-85.9995052603961 34.7796392771775)
3,2022,AL,Alabama,Lauderdale,BRFSS,Health Outcomes,Obesity among adults,%,Age-adjusted prevalence,36.5,...,29.6,43.9,"95,878","77,472",1077,HLTHOUT,OBESITY,AgeAdjPrv,Obesity,POINT (-87.6540983850983 34.9014438477101)
4,2022,AL,Alabama,Lawrence,BRFSS,Disability,Any disability among adults,%,Crude prevalence,40.1,...,35.5,44.7,"33,214","26,022",1079,DISABLT,DISABILITY,CrdPrv,Any Disability,POINT (-87.3108851040374 34.5216735395968)
5,2022,AL,Alabama,Lee,BRFSS,Health Risk Behaviors,Binge drinking among adults,%,Age-adjusted prevalence,15.8,...,12.8,18.8,"180,773","143,546",1081,RISKBEH,BINGE,AgeAdjPrv,Binge Drinking,POINT (-85.3550362108983 32.601254498925)
6,2022,AL,Alabama,Lee,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,3.3,...,3.0,3.6,"180,773","143,546",1081,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-85.3550362108983 32.601254498925)
7,2022,AL,Alabama,Marengo,BRFSS,Health Risk Behaviors,Binge drinking among adults,%,Age-adjusted prevalence,13.7,...,11.0,16.9,"18,745","14,573",1091,RISKBEH,BINGE,AgeAdjPrv,Binge Drinking,POINT (-87.7895124506775 32.2478854975948)
8,2022,AL,Alabama,Marion,BRFSS,Health Outcomes,Stroke among adults,%,Age-adjusted prevalence,4.0,...,3.6,4.3,"29,156","23,044",1093,HLTHOUT,STROKE,AgeAdjPrv,Stroke,POINT (-87.8871984960778 34.1365876476739)
9,2021,AL,Alabama,Mobile,BRFSS,Health Outcomes,High blood pressure among adults,%,Age-adjusted prevalence,38.3,...,35.2,41.6,"411,411","316,433",1097,HLTHOUT,BPHIGH,AgeAdjPrv,High Blood Pressure,POINT (-88.20640909701 30.7791692937068)
10,2022,AL,Alabama,Pickens,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,37.1,...,36.5,37.6,"18,697","15,176",1107,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-88.0891310718596 33.2807870081005)
11,2022,AK,Alaska,Dillingham,BRFSS,Health Outcomes,Obesity among adults,%,Crude prevalence,37.3,...,30.6,44.1,"4,723","3,253",2070,HLTHOUT,OBESITY,CrdPrv,Obesity,POINT (-158.236178154164 59.7978171220014)
12,2022,AK,Alaska,Haines,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,27.3,...,25.8,28.9,"2,056","1,705",2100,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-135.500167586106 59.119335495324)
13,2022,AK,Alaska,Kodiak Island,BRFSS,Health Outcomes,Obesity among adults,%,Age-adjusted prevalence,30.3,...,24.4,36.5,"12,720","9,749",2150,HLTHOUT,OBESITY,AgeAdjPrv,Obesity,POINT (-153.789812278338 57.6808874751479)
14,2022,AZ,Arizona,Yuma,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,26.4,...,26.3,26.5,"207,842","155,973",4027,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-113.905997385394 32.7694427722845)
15,2022,AR,Arkansas,Baxter,BRFSS,Health Outcomes,Diagnosed diabetes among adults,%,Crude prevalence,16.8,...,14.6,19.1,"42,435","34,886",5005,HLTHOUT,DIABETES,CrdPrv,Diabetes,POINT (-92.3369593879758 36.2869936509323)
16,2022,AR,Arkansas,Benton,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,2.9,...,2.6,3.1,"302,863","226,571",5007,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-94.2558310001198 36.3389781548829)
17,2022,AR,Arkansas,Chicot,BRFSS,Health Outcomes,Depression among adults,%,Crude prevalence,23.1,...,19.5,27.0,"9,873","7,738",5017,HLTHOUT,DEPRESSION,CrdPrv,Depression,POINT (-91.2933505574654 33.2667470395332)
18,2022,AR,Arkansas,Columbia,BRFSS,Health Outcomes,Arthritis among adults,%,Age-adjusted prevalence,29.0,...,25.6,32.7,"22,216","17,519",5027,HLTHOUT,ARTHRITIS,AgeAdjPrv,Arthritis,POINT (-93.2275288321248 33.2144070346383)
19,2022,AR,Arkansas,Columbia,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,4.5,...,4.1,4.9,"22,216","17,519",5027,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-93.2275288321248 33.2144070346383)

In [6]:
df.columns.tolist()
df.dtypes

year                            int64
state_abbr                        str
state_desc                        str
location_name                     str
data_source                       str
category                          str
measure                           str
data_value_unit                   str
data_value_type                   str
data_value                    float64
data_value_footnote_symbol     object
data_value_footnote            object
low_confidence_limit          float64
high_confidence_limit         float64
total_population                  str
total_pop_18_plus                 str
location_id                     int64
category_id                       str
measure_id                        str
data_value_type_id                str
short_question_text               str
geolocation                       str
dtype: object

In [7]:
fact_like = [
    "data_value",
    "low_confidence_limit",
    "high_confidence_limit",
    "total_population",
    "total_pop_18_plus",
]

dimension_like = [
    "year",
    "state_abbr",
    "state_desc",
    "location_name",
    "data_source",
    "category",
    "measure",
    "data_value_unit",
    "data_value_type",
    "location_id",
    "category_id",
    "measure_id",
    "data_value_type_id",
    "short_question_text",
    "geolocation",
]

print("Fact-like fields:", fact_like)
print("Dimension-like fields:", dimension_like)

Fact-like fields: ['data_value', 'low_confidence_limit', 'high_confidence_limit', 'total_population', 'total_pop_18_plus']
Dimension-like fields: ['year', 'state_abbr', 'state_desc', 'location_name', 'data_source', 'category', 'measure', 'data_value_unit', 'data_value_type', 'location_id', 'category_id', 'measure_id', 'data_value_type_id', 'short_question_text', 'geolocation']

In [8]:
df[fact_like].head()
df[dimension_like].head()

,year,state_abbr,state_desc,location_name,data_source,category,measure,data_value_unit,data_value_type,location_id,category_id,measure_id,data_value_type_id,short_question_text,geolocation
0,2022,AL,Alabama,Clay,BRFSS,Health Outcomes,Current asthma among adults,%,Crude prevalence,1027,HLTHOUT,CASTHMA,CrdPrv,Current Asthma,POINT (-85.8606604130173 33.2693085517833)
1,2022,AL,Alabama,Dale,BRFSS,Health Outcomes,Arthritis among adults,%,Crude prevalence,1045,HLTHOUT,ARTHRITIS,CrdPrv,Arthritis,POINT (-85.6109266826185 31.4316629601359)
2,2022,AL,Alabama,Jackson,BRFSS,Health Outcomes,Stroke among adults,%,Crude prevalence,1071,HLTHOUT,STROKE,CrdPrv,Stroke,POINT (-85.9995052603961 34.7796392771775)
3,2022,AL,Alabama,Lauderdale,BRFSS,Health Outcomes,Obesity among adults,%,Age-adjusted prevalence,1077,HLTHOUT,OBESITY,AgeAdjPrv,Obesity,POINT (-87.6540983850983 34.9014438477101)
4,2022,AL,Alabama,Lawrence,BRFSS,Disability,Any disability among adults,%,Crude prevalence,1079,DISABLT,DISABILITY,CrdPrv,Any Disability,POINT (-87.3108851040374 34.5216735395968)

In [3]:
engine = create_engine("postgresql+psycopg2://ijeomaokoye@localhost:5432/health_equity")
df = pd.read_sql_query("SELECT * FROM stg_svi LIMIT 20", engine)
display(df)

,st,state,st_abbr,stcnty,county,fips,location,area_sqmi,e_totpop,m_totpop,...,ep_asian,mp_asian,ep_aian,mp_aian,ep_nhpi,mp_nhpi,ep_twomore,mp_twomore,ep_otherrace,mp_otherrace
0,01,Alabama,AL,01001,Autauga County,01001,"Autauga County, Alabama",594.454786355022,58761,0,...,1.1,0.4,0.1,0.1,0.0,0.1,3.3,1.0,0.2,0.3
1,01,Alabama,AL,01003,Baldwin County,01003,"Baldwin County, Alabama",1589.861816637086,233420,0,...,0.9,0.1,0.2,0.1,0.0,0.1,3.1,0.4,0.4,0.3
2,01,Alabama,AL,01005,Barbour County,01005,"Barbour County, Alabama",885.007618621402,24877,0,...,0.5,0.1,0.3,0.1,0.0,0.1,1.8,0.7,1.2,0.8
3,01,Alabama,AL,01007,Bibb County,01007,"Bibb County, Alabama",622.469286466726,22251,0,...,0.3,0.4,0.1,0.1,0.0,0.2,1.7,1.0,0.1,0.1
4,01,Alabama,AL,01009,Blount County,01009,"Blount County, Alabama",644.890376325486,59077,0,...,0.2,0.2,0.1,0.1,0.2,0.2,2.8,0.7,0.1,0.1
5,01,Alabama,AL,01011,Bullock County,01011,"Bullock County, Alabama",622.814753161736,10328,0,...,0.4,0.5,0.0,0.4,0.0,0.4,1.3,1.1,0.0,0.4
6,01,Alabama,AL,01013,Butler County,01013,"Butler County, Alabama",776.838207787896,18981,0,...,1.3,0.3,0.4,0.3,0.0,0.2,1.2,0.6,0.0,0.1
7,01,Alabama,AL,01015,Calhoun County,01015,"Calhoun County, Alabama",605.889936470352,116162,0,...,0.6,0.1,0.1,0.1,0.2,0.2,2.5,0.3,0.4,0.2
8,01,Alabama,AL,01017,Chambers County,01017,"Chambers County, Alabama",596.55406501414,34612,0,...,0.2,0.2,0.0,0.1,0.0,0.1,1.3,0.4,0.2,0.2
9,01,Alabama,AL,01019,Cherokee County,01019,"Cherokee County, Alabama",553.5238774267,25069,0,...,0.1,0.2,0.5,0.3,0.0,0.1,2.8,0.7,0.1,0.1
10,01,Alabama,AL,01021,Chilton County,01021,"Chilton County, Alabama",692.836450870514,45140,0,...,0.5,0.1,0.0,0.1,0.0,0.1,2.1,0.5,0.7,0.5
11,01,Alabama,AL,01023,Choctaw County,01023,"Choctaw County, Alabama",913.478753846466,12669,0,...,0.1,0.2,0.2,0.2,0.0,0.3,2.1,1.3,0.0,0.3
12,01,Alabama,AL,01025,Clarke County,01025,"Clarke County, Alabama",1238.419880434466,23058,0,...,0.4,0.1,0.1,0.1,0.0,0.2,0.8,0.4,0.6,0.4
13,01,Alabama,AL,01027,Clay County,01027,"Clay County, Alabama",603.962148489452,14209,0,...,0.3,0.3,0.0,0.3,0.0,0.3,3.9,1.5,0.1,0.1
14,01,Alabama,AL,01029,Cleburne County,01029,"Cleburne County, Alabama",560.105218450104,15144,0,...,0.1,0.2,0.1,0.2,0.0,0.2,2.0,0.5,0.2,0.2
15,01,Alabama,AL,01031,Coffee County,01031,"Coffee County, Alabama",678.985821932656,53559,0,...,1.1,0.3,0.5,0.2,0.0,0.1,5.0,0.8,0.1,0.1
16,01,Alabama,AL,01033,Colbert County,01033,"Colbert County, Alabama",592.95316193154,57270,0,...,0.4,0.2,0.3,0.2,0.1,0.1,2.2,0.5,0.1,0.2
17,01,Alabama,AL,01035,Conecuh County,01035,"Conecuh County, Alabama",850.278991989168,11576,0,...,0.3,0.3,0.3,0.3,0.0,0.3,1.0,0.6,0.1,0.2
18,01,Alabama,AL,01037,Coosa County,01037,"Coosa County, Alabama",650.908884108226,10329,0,...,0.0,0.4,0.1,0.1,0.0,0.4,2.2,0.9,0.6,0.8
19,01,Alabama,AL,01039,Covington County,01039,"Covington County, Alabama",1030.57016104712,37542,0,...,0.6,0.1,0.3,0.2,0.0,0.1,2.2,0.7,0.2,0.2